---
site_name: "BioData Catalyst Harmonized Model"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2

nav:
  # - Home: home.md
  - Index: index.md
  - About: class-diagram-w-attrs.md
  - Old About: about.md
site_url: https://rtiinternational.github.io/NHLBI-BDC-DMC-HM/
repo_url: https://github.com/RTIInternational/NHLBI-BDC-DMC-HM

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
